### ISSUE TITLE
Aimbot

### ISSUE THREAD

**Issue by LangYa466** [GrimAnticheat/Grim#1319] opened 2024-01-20 05:42 UTC
### Describe the bypass and how to replicate it

HackAimbot that mimics Legit Player Aim
https://github.com/CCBlueX/LiquidBounce/blob/3b6f8c1068255efc795f1dac32265c4e2b5ff42e/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/combat/ModuleAimbot.kt
Here's the code for Liquidbounce

### Grim version

eu.loyisa.cn

### Server version

eu.loyisa.cn

### Plugins

eu.loyisa.cn

**Comment by ManInMyVan** [comment] 2024-01-20 07:12
Duplicate of #1236

**Closed as completed** 2024-01-20 10:07 UTC
Labels: bypass
