### ISSUE TITLE
Noslow bypass

### ISSUE THREAD

**Issue by Dg32z** [GrimAnticheat/Grim#1792] opened 2024-11-13 15:41 UTC
### Describe the bypass and how to replicate it

https://github.com/user-attachments/assets/efb97e24-6573-4bca-b549-1bbb9c00862f

bypass noslow with attack

### Grim version

>ver GrimAC
[23:40:51 INFO]: GrimAC version 2.3.68

[23:40:51 INFO]: Libre simulation anticheat designed for 1.21 with 1.8-1.21 support, powered by PacketEvents 2.0.

[23:40:51 INFO]: Website: https://grim.ac/

[23:40:51 INFO]: Author: GrimAC

>

### Server version

[23:40:58 INFO]: This server is running CraftBukkit version git-PaperSpigot-f6fba00-9935adc (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

[23:40:58 INFO]: Checking version, please wait...

[23:40:59 WARN]: java.io.

### Plugins

[23:40:57 INFO]: Plugins (8): PlugMan, LuckPerms, PlugManX, LiteBans, GrimAC, PlaceholderAPI, SimpleChat, Citizens

**Comment by Dg32z** [comment] 2024-11-13 15:42
only swords

**Comment by ManInMyVan** [comment] 2024-11-13 15:47
duplicate of #1160

**Closed as not planned** 2024-11-13 15:56 UTC
Labels: bypass
