### ISSUE TITLE
Phase (CobbleStone Wall)

### ISSUE THREAD

**Issue by Anthony01M** [GrimAnticheat/Grim#1459] opened 2024-05-05 17:29 UTC
### Describe the false positive and how to replicate it

https://github.com/GrimAnticheat/Grim/assets/33878954/76e5b33f-675f-4a6a-9cb1-8c8dbf1e8a69

can't use /grim log or /grim verbose so:
To false phase just go to a cobblestone wall ( doesn't false if it's 1 but if it's 3 and you go to the one that's in the middle it does false )

### Grim version

according to eu.loyisa.cn; grim version is 2.3.62

### Server version

I believe 1.8

### Plugins

no clue I'm on eu.loyisa.cn

**Comment by Anthony01M** [comment] 2024-05-05 17:32
To be clear, I can't replicate this on a 1.20.4 server version.
Only Client: 1.20.4, Server: 1.8.8 (didn't test anything else atm)

**Comment by ManInMyVan** [comment] 2024-05-06 04:10
Something to do with [DynamicWall](https://github.com/GrimAnticheat/Grim/blob/2.0/src/main/java/ac/grim/grimac/utils/collisions/blocks/connecting/DynamicWall.java)

**Comment by Anthony01M** [comment] 2024-05-09 16:59
I was looking through PRs found out there's a PR that fixes this issue: #1107 
Unfortunately I don't have a 1.8 server available for testing right now due to limited resources.

**Comment by ManInMyVan** [comment] 2024-05-09 18:35
duplicate of #928

**Comment by Axionize** [comment] 2024-12-15 22:12
Should be fixed by https://github.com/GrimAnticheat/Grim/pull/1824

**Closed as completed by Axionize** 2024-12-15 22:12 UTC
Labels: false positive
