### ISSUE TITLE
can't move (again)

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1677] opened 2024-08-22 15:06 UTC
### Describe the bug and how to replicate it

#1676 fixed, but now i can't move when teleport in nether or the end

### Grim version

latest commit

### Server version

1.19.4

### Plugins

grim

**Comment by SamB440** [comment] 2024-08-22 15:19
Unable to reproduce

**Comment by Dbbtop** [comment] 2024-08-22 15:33
> Unable to reproduce

Tomorrow I will sent a video

**Comment by SamB440** [comment] 2024-08-22 15:54
Seems to happen on 1.19.4 clients, but not modern ones

**Comment by Dbbtop** [comment] 2024-08-22 15:57
did you install terralith datapack on 1.19.4 server?

**Comment by Dbbtop** [comment] 2024-08-22 15:58
> did you install terralith datapack on 1.19.4 server?

this is mandatory

**Comment by MichaelKozlovOfficial** [comment] 2024-08-22 15:58
how would he know what to install

**Comment by Dbbtop** [comment] 2024-08-22 16:00
> how would he know what to install

Я русский перепиши сообщение

**Comment by SamB440** [comment] 2024-08-22 16:04
The problem is because the respawn dimension type is latency compensated, whilst the packetevents user was not

I am closing this and reverting the fix I made previously, this needs to be fixed on packetevent's end instead

**Closed as not planned by SamB440** 2024-08-22 16:04 UTC
Labels: bug
