### ISSUE TITLE
Huge spam of false positives in the console of "BadPacketsE"

### ISSUE THREAD

**Issue by Pman3** [GrimAnticheat/Grim#1798] opened 2024-11-15 22:41 UTC
### Describe the false positive and how to replicate it

![image](https://github.com/user-attachments/assets/9c715901-446a-4b01-b118-fa8920a63a7c)
I have my console filled with this from several users. One of the times I saw that this was happening was when a player was riding a horse. I'm unsure why this is happening but I also thought I should maybe share my config since I did make some changes:

https://mclo.gs/jTTtpFC

### Grim version

grimac-2.3.68.jar

### Server version

Paper version 1.21.1-130-ver/1.21.1@4d2672e (2024-10-30T18:33:50Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Client version

1.21 Vanilla

### Plugins

Bukkit Plugins:
AdvancedBan, BukkitRandomMOTD, *ChatCo, ChatControl, DeathMessages, DiscordSRV, EntityDetection, GrimAC, HelpCommand, IllegalStack, *InfoMan, InvSeePlusPlus, JoinDate, LuckPerms, MyCommand, *NitroCommandBlocker, *OldschoolKill, PlaceholderAPI, Plan, ProtocolLib, SuperVanish, TAB, TabCompleteFilter, UltimateAutoRestart, ViaBackwards, ViaVersion, Wild

**Comment by ManInMyVan** [comment] 2024-11-15 22:59
duplicate of #1769

**Closed as not planned** 2024-11-15 23:28 UTC
Labels: false positive
