### ISSUE TITLE
Grim flags Soul Speed as Simulation when Health & Hunger isn't 100%

### ISSUE THREAD

**Issue by VibinHippo** [GrimAnticheat/Grim#1580] opened 2024-06-30 05:07 UTC
### Describe the false positive and how to replicate it
This arises when health and hunger are not full: 
1. When walking on soul sand with any level of soul speed, Grim flags as Simulation: 
Grim » <player> failed Simulation (x200) .072644 /gl 3
2. Also happens when using swift sneak

### Grim version

v2.3.65

### Server version

Paper 1.21, Build #39 (MC: 1.21)

### Plugins

BetterSleeping4, BlockLocker, ClearLag, GrimAC, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LuckPerms, SimpleTpa

**Comment by okunamayanad** [comment] 2024-07-06 08:33
Grim flags soul speed and swift sneak as "Simulation" even while health & hunger is 100% for me 

<details>
<summary>Server version 1.21-44</summary>

```
This server is running Paper version 1.21-44-master@8d91b85 (2024-07-04T18:56:20Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-40-b45d9b6 (MC: 1.21)
```

</details>

Grim AC Version: 2.3.65

**Comment by SamB440** [comment] 2024-07-06 09:06
Duplicate of #1583

**Closed as not planned by SamB440** 2024-07-06 09:06 UTC
Labels: false positive
