### ISSUE TITLE
NoSlow

### ISSUE THREAD

**Issue by LangYa466** [GrimAnticheat/Grim#1312] opened 2024-01-20 05:30 UTC
### Describe the bypass and how to replicate it

There is no slowdown, just send 2 C09 SwitchItems in the MotionPre Event, and then send a TryUseItem in the MotionPost time to use the item to bypass

### Grim version

eu.loyisa.cn

### Server version

eu.loyisa.cn

### Plugins

eu.loyisa.cn

**Comment by ManInMyVan** [comment] 2024-01-20 07:10
Duplicate of #1091

**Closed as completed** 2024-01-20 10:08 UTC
Labels: bypass
