### ISSUE TITLE
AirLiquidPlace false flag

### ISSUE THREAD

**Issue by Dg32z** [GrimAnticheat/Grim#1776] opened 2024-11-07 16:09 UTC
### Describe the false positive and how to replicate it

Right click with the mouse while breaking the block

https://github.com/user-attachments/assets/3f18f54b-8fc9-4198-9421-31bdf2502f47

### Grim version

https://github.com/GrimAnticheat/Grim/actions/runs/11632786554

### Server version

> ver
[00:08:22 INFO]: Checking version, please wait...
[00:08:23 INFO]: This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-128-d348cb8 (MC: 1.21.1)

### Client version

vanilla 1.20.4

### Plugins

[00:08:37 INFO]: Server Plugins (10):
[00:08:37 INFO]: Bukkit Plugins:
[00:08:37 INFO]:  - Apollo-Bukkit, Citizens, GrimAC, LiteBans, LuckPerms, LunarPlugin, PlaceholderAPI
[00:08:37 INFO]:  PlugManX, SimpleChat, TAB

**Comment by Axionize** [comment] 2024-11-08 02:45
Known Issue. Exempt for it if you care about people left and right clicking at the same time. I might get around to fixing it after I finish expanding Line of Sight Place to work for block breaks as well.

**Comment by ManInMyVan** [comment] 2024-11-18 06:06
duplicate of #1649

**Closed as completed** 2024-12-07 16:13 UTC
Labels: false positive
