### ISSUE TITLE
Stacktrace on /grim spectate while using Folia

### ISSUE THREAD

**Issue by BigPebble123** [GrimAnticheat/Grim#1753] opened 2024-10-09 09:01 UTC
### Stack trace

```
[08:57:23 ERROR]: [GrimAC] [ACF] Exception in command: grim spectate [REDACTED]
[08:57:23 ERROR]: [GrimAC] [ACF] java.lang.UnsupportedOperationException: Must use teleportAsync while in region threading
[08:57:23 ERROR]: [GrimAC] [ACF]        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1413)
[08:57:23 ERROR]: [GrimAC] [ACF]        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1362)
[08:57:23 ERROR]: [GrimAC] [ACF]        at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:233)
[08:57:23 ERROR]: [GrimAC] [ACF]        at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:303)
[08:57:23 ERROR]: [GrimAC] [ACF]        at grimac-2.3.67.jar//ac.grim.grimac.commands.GrimSpectate.onSpectate(GrimSpectate.java:55)
[08:57:23 ERROR]: [GrimAC] [ACF]        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[08:57:23 ERROR]: [GrimAC] [ACF]        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[08:57:23 ERROR]: [GrimAC] [ACF]        at grimac-2.3.67.jar//ac.grim.grimac.shaded.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[08:57:23 ERROR]: [GrimAC] [ACF]        at grimac-2.3.67.jar//ac.grim.grimac.shaded.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[08:57:23 ERROR]: [GrimAC] [ACF]        at grimac-2.3.67.jar//ac.grim.grimac.shaded.acf.BaseCommand.execute(BaseCommand.java:513)
[08:57:23 ERROR]: [GrimAC] [ACF]        at grimac-2.3.67.jar//ac.grim.grimac.shaded.acf.RootCommand.execute(RootCommand.java:99)
[08:57:23 ERROR]: [GrimAC] [ACF]        at grimac-2.3.67.jar//ac.grim.grimac.shaded.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[08:57:23 ERROR]: [GrimAC] [ACF]        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[08:57:23 ERROR]: [GrimAC] [ACF]        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.Commands.performCommand(Commands.java:350)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.Commands.performCommand(Commands.java:337)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.commands.Commands.performCommand(Commands.java:332)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2270)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2244)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$tryHandleChat$17(ServerGamePacketListenerImpl.java:2408)
[08:57:23 ERROR]: [GrimAC] [ACF]        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:181)
[08:57:23 ERROR]: [GrimAC] [ACF]        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1711)
[08:57:23 ERROR]: [GrimAC] [ACF]        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407)
[08:57:23 ERROR]: [GrimAC] [ACF]        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418)
[08:57:23 ERROR]: [GrimAC] [ACF]        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540)
[08:57:23 ERROR]: [GrimAC] [ACF]        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to replicate it if known

1. Use Folia
2. Try to spectate a player
3. Get an error

### Grim version

2.3.67

### Server version

This server is running Folia version 1.21.1-DEV-dev/1.21.1@88e0907 (2024-10-08T03:33:02Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugins

n/a

**Comment by ManInMyVan** [comment] 2024-11-18 06:08
duplicate of #1540

**Closed as not planned** 2024-11-18 11:06 UTC
Labels: error
