### ISSUE TITLE
AntiKB/Explosion false with explosions

### ISSUE THREAD

**Issue by Jyguy** [GrimAnticheat/Grim#619] opened 2022-07-05 14:27 UTC
**Describe the bug**
When an explosion (in this case, crystals/respawn anchors) happens near a player one block above their location, it false flags AntiKB quite often with Explosion flagging rarely. Testing was done on a vanilla 1.16.5 client.

**To Reproduce**
https://youtu.be/E2g0_j2bKdA (crystals)
https://youtu.be/_5CWpeFpt30 (anchors)

**Server Version:**
This server is running Paper version git-Paper-"fa1a7c180" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Grim Version (Git commit or the version in the jar's name)**
2c3a6acc4ebad00a91bce18a77542b1e7af39fba

**Relevant plugins**
Plugins (1): GrimAC

**Comment by MWHunter** [comment] 2022-07-06 00:16
unable to reproduce

**Comment by Jyguy** [comment] 2022-07-06 11:59
Found a pretty consistent way to reproduce. Being 2 blocks away from the exploding block with 2 blocks stopping you from being knocked away (see https://youtu.be/xIWElfyE1dU) flags it almost every single time. I'm also able to reproduce it on 1.17.1 and 1.18.2, and the clip is in 1.18.2.

**Comment by MWHunter** [comment] 2022-07-07 02:23
wasn't able to reproduce since I was in godmode and the knockback was required

fixed by https://github.com/MWHunter/Grim/commit/377010e7203ed55ac4d129294f1a606228d87853

**Closed as completed by MWHunter** 2022-07-07 02:23 UTC
Labels: bug
