### ISSUE TITLE
Failed Bad Packets false positive fully restricts player movement on all mc versions below 1.17

### ISSUE THREAD

**Issue by MithrandirCraft** [GrimAnticheat/Grim#1344] opened 2024-01-30 13:01 UTC
### Describe the false positive and how to replicate it

Just install grimac on a clean paper server with viaversion, viarewind (and optionally viabackwards), then connect to the server using a client version below 1.17 (that is 1.16.2 or lower).

If you're an admin you should notice the Bad Packets false positive messages in chat.

PadPackets check should either be adjusted for clients below 1.17, disabled, or there should be a workaround.

![imagen](https://github.com/GrimAnticheat/Grim/assets/6623704/ce9888a4-fc2b-4c12-97cf-bd8b2583cda2)

### Grim version

2.3.55

### Server version

1.20.2 (with all via* plugins installed)

### Plugins

Server Plugins (50):
Paper Plugins:
- AuthMeVelocity, MarriageMaster
Bukkit Plugins:
- 40ServidoresMC, AdvancedPortals, AuthMe, BanFromClaim, BetterRTP, BottledExp, ChatControlRed, ClearLag, CMILib, CoreProtect
CraftingStore, CrazyCrates, CustomJukebox, DecentHolograms, DownloadResourcePack, ElytraBalance, Essentials, EssentialsSpawn, FastAsyncWorldEdit, FastLogin
floodgate, GriefDefender, GrimAC, Guilds, JukeboxRegion, LibsDisguises, LuckPerms, MythicMobs, NerfVillages, PlaceholderAPI
PlayerHeads, PlayerWarps, PremiumVanish, ProtocolLib, Shopkeepers, SkinsRestorer, SSX-Connector, *StatsPvP, Storage, TAB-Bridge
TradeSystem, Vault, ViaBackwards, ViaRewind, ViaVersion, ViewDistanceTweaks, VotingPlugin, WorldGuard

**Comment by SamB440** [comment] 2024-01-30 13:06
BadPacketsN means you are ignoring teleports. Please try and reproduce with only GrimAC and via installed.

**Comment by MithrandirCraft** [comment] 2024-01-30 14:58
It's happening only on my survival server with only grimac, ViaBackwards, ViaRewind & ViaVersion installed.

It's likely to be server/config related, but I still haven't pinpointed what.

What is this teleportation ignore you mention? Maybe a server config?

**Comment by SamB440** [comment] 2024-01-30 15:16
I am saying that BadPacketsN flags because Grim believes your client has ignored a teleport packet.

I can't reproduce this problem with a 1.20.2 Paper server and a 1.12.2 vanilla client.

**Comment by MithrandirCraft** [comment] 2024-01-30 15:52
Just noticed it actually does happen on every server on my network, velocity related?

**Comment by MithrandirCraft** [comment] 2024-01-31 14:44
Fixed: Issue was I had left the via* plugins on velocity, as well as on every backend server.

Big fail.

**Comment by SamB440** [comment] 2024-02-03 09:26
Please close this issue, then

**Closed as completed** 2024-05-02 19:54 UTC
Labels: false positive

**Comment by rajatmodi45** [comment] 2024-06-16 07:55
> Fixed: Issue was I had left the via* plugins on velocity, as well as on every backend server.
> 
> Big fail.

i didnt understand the same thing is with me can you explain me how to fix this issue
