### ISSUE TITLE
Vpae Client Bypassing Grim reach check

### ISSUE THREAD

**Issue by fodded** [GrimAnticheat/Grim#1231] opened 2023-11-28 11:50 UTC
### Describe the bypass and how to replicate it

Vape client using function BackTrack is bypassing Grim. It doesn't detect this at all. BackTrack is basically reach

### Grim version

The latest from the github

### Server version

1.8.8 paper

### Plugins

My custom + grimac

**Comment by Souipi** [comment] 2023-11-29 00:10
i don't think BackTrack can't be detected. And imo that not a real " reach "

**Comment by overkidding** [comment] 2023-11-29 00:30
> ### Describe the bypass and how to replicate it
> Vape client using function BackTrack is bypassing Grim. It doesn't detect this at all. BackTrack is basically reach
> 
> ### Grim version
> The latest from the github
> 
> ### Server version
> 1.8.8 paper
> 
> ### Plugins
> My custom + grimac

Settings of vape backtrack

**Comment by c0dingnoobi** [comment] 2023-11-29 14:06
(vapes backtrack is invalid and flags reach)

**Comment by CuteistCat** [comment] 2024-03-19 20:34
Backtrack is emulated lag so i dont think it can be patched without a lot of faslo positives. But im not a ac dev so im not sure

**Comment by ManInMyVan** [comment] 2024-06-29 18:27
duplicate of #545

**Closed as not planned** 2024-08-20 10:04 UTC
Labels: bypass
