### ISSUE TITLE
Bed issues

### ISSUE THREAD

**Issue by DasCanard** [GrimAnticheat/Grim#1058] opened 2023-06-17 21:40 UTC
### Describe the false positive and how to replicate it

1. Look video: https://youtu.be/JOCJ8OvLqOg
2. Logs: https://paste.grim.ac/HTVeo

### Grim version

1bed34d73c477861694ef5244aba8715944cd059

### Server version

Paper version git-Paper-545 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bacbf86)

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/17070204/8b06da46-e15a-401f-bec1-6ad096e8d910)
Matrix does not affect the issues, tested it without.

**Comment by booky10** [comment] 2023-06-18 01:51
probably duplicate of #760

ive implemented a fix for this on a fork (c3cfe2e807651881b9d3233e33527a96d2f2dcc5), but im not sure how this affects other versions, as i didnt test it properly yet

**Closed as not planned** 2023-06-18 16:08 UTC
Labels: false positive
