### ISSUE TITLE
FastBreak

### ISSUE THREAD

**Issue by TomikQu** [GrimAnticheat/Grim#1586] opened 2024-07-07 18:37 UTC
### Describe the false positive and how to replicate it

FastBreak falsely detects FastBreak when someone has efficiency 

### Grim version

2.3.65

### Server version

This server is running Paper version 1.21-46-master@2fa5e0e (2024-07-06T21:32:48Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-44-8d91b85 (MC: 1.21)

### Plugins

![obraz_2024-07-07_203656208](https://github.com/GrimAnticheat/Grim/assets/111223430/00cd45fb-2cde-4814-a9cc-07ec25587f45)

**Comment by SamB440** [comment] 2024-07-07 19:26
Duplicate of #1583

**Closed as not planned by SamB440** 2024-07-07 19:26 UTC
Labels: false positive
