### ISSUE TITLE
Setbacks due to jump potion desync

### ISSUE THREAD

**Issue by D4mian1** [GrimAnticheat/Grim#1515] opened 2024-06-07 07:09 UTC
### Describe the false positive and how to replicate it

GroundSpoof

### Grim version

![image](https://github.com/GrimAnticheat/Grim/assets/172015248/eecdb932-1481-49e6-9a4d-18b8a056e36b)
https://youtu.be/IobjUyoI-ys

### Server version

1.8.9

### Plugins

-

**Comment by SamB440** [comment] 2024-06-07 20:16
Caused by plugins spamming a "REMOVE EFFECT" packet along with a "ADD EFFECT" packet every tick. Plugins should instead reapply the effect, not remove then readd.

This is unlikely to be fixed in Grim - I believe it's due to transaction splits.

**Comment by SamB440** [comment] 2024-06-24 11:40
Can you try this on the latest commit?

**Comment by Anthony01M** [comment] 2024-07-01 05:19
@D4mian1 have you tried on latest commit? Does this still happen? Can we close this?

**Closed as completed** 2024-07-02 12:20 UTC
Labels: false positive
