### ISSUE TITLE
Can't break logs | 1.20.4, latest version of Grim

### ISSUE THREAD

**Issue by StKillReal** [GrimAnticheat/Grim#1260] opened 2023-12-21 19:26 UTC
### Describe the false positive and how to replicate it

Just try to break a tree with axe enchanted on effeciency 

### Grim version

2.3.49 patch 1

### Server version

![image](https://github.com/GrimAnticheat/Grim/assets/60330193/069e55b0-5b84-48b6-b6aa-a4610831b97e)

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/60330193/4bb7e5f4-7c82-4be5-817e-92a6d7485b60)

**Comment by SamB440** [comment] 2023-12-21 22:06
Duplicate of #1253

**Closed as completed** 2024-01-01 11:55 UTC
Labels: false positive
