### ISSUE TITLE
Backtrack

### ISSUE THREAD

**Issue by LangYa466** [GrimAnticheat/Grim#1317] opened 2024-01-20 05:38 UTC
### Describe the bypass and how to replicate it

https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/combat/ModuleBacktrack.kt
Here's Liquidbounce's code for his Backtrack to bypass New Grim

### Grim version

eu.loyisa.cn

### Server version

eu.loyisa.cn

### Plugins

eu.loyisa.cn

**Comment by ManInMyVan** [comment] 2024-01-20 07:11
Impossible to flag accurately without flagging laggy players, also duplicate of #545

**Closed as completed** 2024-01-20 10:08 UTC
Labels: bypass
