### ISSUE TITLE
1.8 BadPacketsN Spam

### ISSUE THREAD

**Issue by xxKraken** [GrimAnticheat/Grim#823] opened 2022-12-09 08:14 UTC
### Describe the false positive and how to replicate it

Log in to a 1.8 vanilla spigot server with 1.18+ (1.18.2 used for this) using viaversion 4.5.0 and badpacketsn will trigger every time and reset your position to yaw 0, pitch 0, the spam part of this thread comes from actual players playing, you will see huge violations from players seemingly just running around regularly, Verbose & an alt account must be enabled to see the violation on join from BadPacketsN

This issue did not occur on the prior 4.4.0 viaversion grim anticheat

### Grim version

Grim Version 2.3.26

### Server version

git-Spigot-21fe707-741a1bd (MC: 1.8.8)

### Plugins

WorldEdit, PlugMan, ViaVersion, WorldBorder, Vault, ProtocolLib, Essentials, EssentialsChat, GrimAC, EssentialsSpawn

**Comment by MWHunter** [comment] 2022-12-10 00:13
Most likely caused by ViaVersion and not grim.

**Comment by xxKraken** [comment] 2022-12-10 00:48
Is it possible to get this fixed if it is viaversion, I had to disable grim for the time being due to the random lag backs

**Comment by MWHunter** [comment] 2022-12-11 22:23
affects all pre-1.17 clients on 1.17+ servers due to via's incorrect mapping of pings

**Comment by MWHunter** [comment] 2022-12-12 00:02
seems to actually be a packetevents issue

**Comment by MWHunter** [comment] 2022-12-12 00:02
I'd suggest using the spigot build as it uses an outdated packetevents and is therefore stable

**Comment by xxKraken** [comment] 2022-12-12 01:20
The issue still occurs on 2.3.27 (spigot-grim), I'll just downgrade back to viaversion 4.4.0 and use a grim version prior to 1.19.3 update for the time being seeing as you've somewhat spotted the issue I have faith it'll be fixed eventually

**Comment by MWHunter** [comment] 2022-12-12 01:30
Fixed by 
https://github.com/GrimAnticheat/Grim/commit/59e01015944e3358971def920a56a5b716db1427

https://github.com/retrooper/packetevents/commit/8c6865405df968a21ef9529cfe448ae3ba66ed51

**Closed as completed by MWHunter** 2022-12-12 01:30 UTC
Labels: viaversion, false positive
