### ISSUE TITLE
Simulation false when player use the swift_sneak enchantment

### ISSUE THREAD

**Issue by Dg32z** [GrimAnticheat/Grim#1588] opened 2024-07-13 08:15 UTC
### Describe the false positive and how to replicate it

https://paste.grim.ac/xjd4t4w

https://github.com/user-attachments/assets/d8686fe8-c813-4579-846a-824ef0483242

### Grim version

[https://github.com/GrimAnticheat/Grim/actions/runs/9875328337](url)

### Server version

> ver
[16:14:15 INFO]: Checking version, please wait...
[16:14:18 INFO]: This server is running Paper version 1.21-54-master@f250ec0 (2024-07-11T16:05:17Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Plugins

[16:14:33 INFO]: Server Plugins (8):
[16:14:33 INFO]: Bukkit Plugins:
[16:14:33 INFO]:  - GrimAC, LiteBans, LuckPerms, packetevents, PlaceholderAPI, ProtocolLib, spark

**Comment by SamB440** [comment] 2024-07-13 09:59
Duplicate of #1583

**Closed as not planned by SamB440** 2024-07-13 09:59 UTC
Labels: false positive
