### ISSUE TITLE
Describe the bypass and how to replicate it

### ISSUE THREAD

**Issue by MitroxYT** [GrimAnticheat/Grim#1455] opened 2024-05-03 17:30 UTC
### Describe the bypass and how to replicate it

```java
    private void handleRwMode(NoSlowEvent noSlow) {
        boolean offHandActive = mc.player.isHandActive() && mc.player.getActiveHand() == Hand.OFF_HAND;
        boolean mainHandActive = mc.player.isHandActive() && mc.player.getActiveHand() == Hand.MAIN_HAND;
        if (!(mc.player.getItemInUseCount() < 25 && mc.player.getItemInUseCount() > 4) && mc.player.getHeldItemOffhand().getItem() != Items.SHIELD) {
            return;
        }
        if (mc.player.isHandActive() && !mc.player.isPassenger()) {
            mc.playerController.syncCurrentPlayItem();
            if (offHandActive && !mc.player.getCooldownTracker().hasCooldown(mc.player.getHeldItemOffhand().getItem())) {
                int old = mc.player.inventory.currentItem;
                mc.player.connection.sendPacket(new CHeldItemChangePacket(old + 1 > 8 ? old - 1 : old + 1));
                mc.player.connection.sendPacket(new CHeldItemChangePacket(mc.player.inventory.currentItem));
                noSlow.cancel();
            }

            if (mainHandActive && !mc.player.getCooldownTracker().hasCooldown(mc.player.getHeldItemMainhand().getItem())) {
                mc.player.connection.sendPacket(new CPlayerTryUseItemPacket(Hand.OFF_HAND));

                if (mc.player.getHeldItemOffhand().getUseAction().equals(UseAction.NONE)) {
                    noSlow.cancel();
                }
            }
            mc.playerController.syncCurrentPlayItem();
        }
    }
    ```
    work in mainhand on offhand no bypass
    

### Grim version

latest

### Server version

1.16.5

### Plugins

GrimAC Protocollib

**Comment by ManInMyVan** [comment] 2024-05-03 18:05
> latest

Not helpful, is it the latest release, or the latest commit?

**Comment by MitroxYT** [comment] 2024-05-04 19:08
last commit

**Comment by Symmettry** [comment] 2024-05-08 00:39
ok but you're meant to actually *describe the bypass* not just say it. what is this doing? noslow? autoblock?

**Comment by ManInMyVan** [comment] 2024-05-08 01:34
Duplicate of #1444

**Comment by MitroxYT** [comment] 2024-05-08 18:49
Noslow Bypass

**Closed** 2024-07-29 23:47 UTC
Labels: bypass
