### ISSUE TITLE
Camel jump

### ISSUE THREAD

**Issue by Madimus** [GrimAnticheat/Grim#1267] opened 2023-12-23 21:29 UTC
### Describe the false positive and how to replicate it

1. Ride a camel
2. Try jump
3. You will get trown off camel

### Grim version

2.3.49

### Server version

1.20.1

### Plugins

GrimAC

**Comment by SamB440** [comment] 2023-12-24 12:04
Duplicate of #1157 #1059

#1165 

Camels are not implemented yet

**Closed as completed** 2023-12-24 15:27 UTC
Labels: false positive
