### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by SkirmisLTU** [GrimAnticheat/Grim#1255] opened 2023-12-17 09:18 UTC
### Stack trace

[07:28:06] [Server thread/INFO]: serhat212107 joined the server
[07:28:06] [Server thread/INFO]: serhat212107[/78.***.146.***:54739] logged in with entity id 326 at ([world]-1296.5406963547646, 89.0, 375.35421051616026)
[07:28:06] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: Can't get common connection state: LOGIN != CONFIGURATION
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.player.User.getConnectionState(User.java:77) ~[grimac-2.3.49.jar:?]
	at ac.grim.grimac.player.GrimPlayer.sendTransaction(GrimPlayer.java:360) ~[grimac-2.3.49.jar:?]
	at ac.grim.grimac.events.packets.PacketEntityReplication.onEndOfTickEvent(PacketEntityReplication.java:444) ~[grimac-2.3.49.jar:?]
	at ac.grim.grimac.manager.init.start.TickEndEvent.tickRelMove(TickEndEvent.java:25) ~[grimac-2.3.49.jar:?]
	at ac.grim.grimac.manager.init.start.TickEndEvent.access$000(TickEndEvent.java:19) ~[grimac-2.3.49.jar:?]
	at ac.grim.grimac.manager.init.start.TickEndEvent$1.onIterator(TickEndEvent.java:51) ~[grimac-2.3.49.jar:?]
	at ac.grim.grimac.utils.lists.HookedListWrapper.iterator(HookedListWrapper.java:35) ~[grimac-2.3.49.jar:?]
	at java.util.Collections$SynchronizedCollection.iterator(Collections.java:2100) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:232) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[07:28:07] [Server thread/ERROR]: This crash report has been saved to: *****************************/crash-reports/crash-2023-12-17_07.28.07-server.txt
[07:28:07] [Server thread/INFO]: Stopping server

### Grim version

2.3.49

### Server version

Purpur-2094 1.20.2

### Plugins

- AdvancedPortals, AdvancedRegionMarket, BanItem, BetterShulkerBoxes, BuycraftX, ChatFilter, ChatManager, Citizens, ClansLite, ClearLag, CMI, CMILib, CommandPanels, CommandWhitelist, CoreProtect, DamageReduction, DecentHolograms, *DiscordUtils, DropEdit2, ExcellentCrates, FastAsyncWorldEdit, GrimAC, HeadDatabase, IllegalStack, InventoryRollbackPlus, ItemEdit, ItemTag, JPremium, LiteBans, LuckPerms, MineResetLite, *MVdWPlaceholderAPI, MyCommand, NexEngine, PlaceholderAPI, Plan, PlayerVaults, PlugManX, PolarLoader, PremiumVanish, ProtocolLib, PvPManager, SelectionVisualizer, Shopkeepers, Skellett, Skript, *skript-placeholders, *skUtilities, spark, TAB-Bridge, TradeMe, *TSetSpawn, Vault, ViaBackwards, ViaVersion, VoidGen, VotifierPlus, VotingPlugin, Vulcan, WG-GUI, WizardDamageReduction, WorldGuard, WorldGuardExtraFlags

**Comment by Souipi** [comment] 2023-12-18 15:46
I don't have the problem on the same config. So it's probably one of your plugin that causes the problem

**Comment by MWHunter** [comment] 2023-12-18 19:41
This is a packetevents issue or a plugin incompatibility, not a grim issue.

**Comment by jordoncodes** [comment] 2023-12-19 11:18
I'm getting the same issue, Purpur 1.20.2. might be purpur? plugins we have in common to maybe help you figure out what it is: grim ac (duh), LuckPerms, PlugManX, spark, FastAsyncWorldEdit, WorldGuard, ViaVersion, Vault

edit: swapped to Paper 1.20.2, still have the same crash

**Comment by SkirmisLTU** [comment] 2023-12-19 17:09
@jordoncodes Are you using bungee? What plugins on bungee?

**Comment by SkirmisLTU** [comment] 2023-12-19 17:14
> This is a packetevents issue or a plugin incompatibility, not a grim issue.

Maybe there is a way to make it only kick the player, and avoid full server crash? Also, as far as I know there is lot of stuff with spigot API and stuff on 1.20.2 so there might be a chance that his is grim issue (can you double check pleaseee?).

**Comment by SamB440** [comment] 2023-12-19 18:00
I have ran multiple PacketEvents plugins on a 1.20.2 Paper server for months and never had any issues like this.

Also: https://github.com/retrooper/packetevents/issues/628
The error posted here is not the full error, it's https://mclo.gs/9iScQzZ. 

You are also running Polar AND Vulcan alongside Grim, running this many anticheats together is just asking for problems, especially when Polar specifically states it's incompatible in that way.

**Comment by SkirmisLTU** [comment] 2023-12-19 18:03
I tried running it without Polar and Vulcan; same result, so they're not the problem. Additionally, there is currently no effective anticheat available. Therefore, I am forced to combine the best features from all of the anticheats.

**Comment by SamB440** [comment] 2023-12-19 18:08
I am running all of the plugins @jordoncodes said they had in common with you and as mentioned I haven't had any issues. This needs viable reproduction steps with only Grim and/or PacketEvents installed, otherwise nothing much can be done really.

edit: I am behind a Velocity proxy btw

**Comment by SkirmisLTU** [comment] 2023-12-19 20:39
I finally found a way to reproduce it:

Plugins - GrimAC, JPremium, ProtocolLib, spark, ViaBackwards, ViaVersion

Server version: Purpur 1.20.2 build 2095
Client: 1.20.2
Logs: https://mclo.gs/ND2RbOV
Bungee: XCord 1.56 (it's probably the same with any bungee)

Grim configuration: 
[config.txt](https://github.com/retrooper/packetevents/files/13720111/config.txt)
(rename it to `config.yml` if you're planning to use it)


Reproduce steps:
1. Join the server
2. Leave the server
3. Join the server again
4. Watch it crash

(!) I believe that `enable-post-packet: true` config option makes it crash

**Comment by SamB440** [comment] 2023-12-19 21:01
Minus XCord and JPremium, as both of those cost money, I created a bungeecord proxy with the default setup and a backend server of the same version you stated, plugins and the config you provided, and I can't reproduce the problem. Please try and reproduce this with vanilla bungeecord and/or without JPremium.

**Comment by jordoncodes** [comment] 2023-12-20 00:01
> @jordoncodes Are you using bungee? What plugins on bungee?

i had no proxy at all

**Comment by SkirmisLTU** [comment] 2023-12-20 15:53
Here is more accurate way to reproduce:
1. Create a bungeecord server, then server1 and server2 (make them connected trough Bungeecord).
2. Place grim in server1 (idk if you need it in server2).
3. Join server 1 trough bungee.
4. Execute this command in bungee: /send your_username server2
5. Execute this command in bungee: /send your_username server1
6. Server crashes.

Here a download to my setup that reproduces the bug: https://www.mediafire.com/file/22k12irwv38f85k/Grim_crash.zip/file
(feel free to replace all server.jar and plugins if you don't trust me:D)

**Comment by SamB440** [comment] 2023-12-20 17:30
I can reproduce it with that setup and it's due to 1.20.2+ changes. The encoder and decoder state got split in packetevents and they can be desynced, looking into a fix.

Edit:
@SkirmisLTU @jordoncodes Please try and see if the issue is fixed by https://github.com/SamB440/Grim/actions/runs/7278880838/artifacts/1127153102

**Comment by SkirmisLTU** [comment] 2023-12-20 17:54
It works as expected now. Thank you for the fix!


**One more thing.**

There is elytra false positive on 1.20.2 (+other versions maybe?) when player is using 1.16.x client (with [ViaBackwards](https://github.com/ViaVersion/ViaBackwards)).
I don't know if I need to create another issue, but I will provide preproduce steps here:
1. Create 1.20.2 server with grim and [ViaBackwards](https://github.com/ViaVersion/ViaBackwards) installed.
2. Join with 1.16.x client (mostly, I saw players with 1.16.4 false, so that's what I recommend)
3. Equip elytra and get fireworks
4. Mess around with them for a few minutes (it mostly occurs when taking off with elytra using fireworks) and you will get it to false

**Closed as completed** 2023-12-20 19:45 UTC
Labels: error
