### ISSUE TITLE
CrashD false positive on placing item in the hopper

### ISSUE THREAD

**Issue by StKillReal** [GrimAnticheat/Grim#1265] opened 2023-12-23 11:52 UTC
### Describe the false positive and how to replicate it

When players try to add item in hopper, they can't
![image](https://github.com/GrimAnticheat/Grim/assets/60330193/31014f42-2360-428a-a778-18726a10b782)

### Grim version

the lastest

### Server version

![image](https://github.com/GrimAnticheat/Grim/assets/60330193/ecc6d53b-09df-43cc-8889-bfda8b062b6d)

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/60330193/15780097-0415-41eb-b962-41bafcb09787)

**Comment by SamB440** [comment] 2023-12-23 12:55
Can't reproduce, please provide exact reproduction steps including what keys were pressed / the method used to move the item into the hopper.

**Comment by StKillReal** [comment] 2023-12-23 16:23
> Can't reproduce, please provide exact reproduction steps including what keys were pressed / the method used to move the item into the hopper.

So, players just open hopper and can't place items into it. When i asked try faster, I saw this grim alerts in chat

**Comment by SamB440** [comment] 2023-12-23 17:23
Well they're either cheating or using some mod IMO

**Comment by StKillReal** [comment] 2024-01-01 20:43
> Well they're either cheating or using some mod IMO

So i have not been using grim for a while to wait for fix. I still have the same issue with players even on vanilla game version. 
![image](https://github.com/GrimAnticheat/Grim/assets/60330193/c755a8ca-0b46-4b1a-ad85-ea7b508af850)

When I use these settings, nothing changes, but I don't see alerts in chat
![image](https://github.com/GrimAnticheat/Grim/assets/60330193/886a2112-77c7-40bb-bdab-a3fafe5af841)
**Players can put items in hopper, but when they close it, items appears in the invenroty. Even if u change slot of the item inside ur inventory while hopper invenotory is open and then close hopper - all items will back to their previos slot**

Idk if it can cause the issue, but I can use hoppers with all grim permissions
![image](https://github.com/GrimAnticheat/Grim/assets/60330193/2ff1b97a-3185-4c01-bc10-17d807728efd)

**Comment by StKillReal** [comment] 2024-01-01 21:03
> > Well they're either cheating or using some mod IMO
> 
> So i have not been using grim for a while to wait for fix. I still have the same issue with players even on vanilla game version. ![image](https://private-user-images.githubusercontent.com/60330193/293606483-c755a8ca-0b46-4b1a-ad85-ea7b508af850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNDI5MDgsIm5iZiI6MTcwNDE0MjYwOCwicGF0aCI6Ii82MDMzMDE5My8yOTM2MDY0ODMtYzc1NWE4Y2EtMGI0Ni00YjFhLWFkODUtZWE3YjUwOGFmODUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDIwNTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MzU0NGMwZjdhZmQ2NmEzYmZmZTg2M2RiZTM1ZDAzMGUxOWU1YjgxZTljMDBiNmI5ODk2ZWMwZTQ0NDVkNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oDPWd8sNs8FPmU-ppiWbaU3us-ieRrcdNPKKR47S_MA)
> 
> When I use these settings, nothing changes, but I don't see alerts in chat ![image](https://private-user-images.githubusercontent.com/60330193/293606487-886a2112-77c7-40bb-bdab-a3fafe5af841.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNDI5MDgsIm5iZiI6MTcwNDE0MjYwOCwicGF0aCI6Ii82MDMzMDE5My8yOTM2MDY0ODctODg2YTIxMTItNzdjNy00MGJiLWJkYWItYTNmYWZlNWFmODQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDIwNTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NjE0N2I0NTE5OGYxYmY2YTRmMDYyNWZkYjAxY2I3NzIwMDNiZTViOTA2YTBiN2I2MGYwM2NlZDU3Y2E0ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7M0Bc3WVEqTREl4OjMdmOYj3A_CZoflnIY4ouiNJlbA) **Players can put items in hopper, but when they close it, items appears in the invenroty. Even if u change slot of the item inside ur inventory while hopper invenotory is open and then close hopper - all items will back to their previos slot**
> 
> Idk if it can cause the issue, but I can use hoppers with all grim permissions ![image](https://private-user-images.githubusercontent.com/60330193/293606611-2ff1b97a-3185-4c01-bc10-17d807728efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNDI5MDgsIm5iZiI6MTcwNDE0MjYwOCwicGF0aCI6Ii82MDMzMDE5My8yOTM2MDY2MTEtMmZmMWI5N2EtMzE4NS00YzAxLWJjMTAtMTdkODA3NzI4ZWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDIwNTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MzgwZWIzZWMxYzE4ODk1MmFkMjNhOGVhZTQwYWQ2ZDllZmM2YmE4NzM4YWE1NjFiNzIwMWEwYmU2OTRiMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5u2sSVy4zHtCLzhY16bAcoja9PH6vIwnvWyLPtPL1Lg)

I have tried to delete all plugins, exept of grim and reset grim folder. Nothing changed

**Comment by SamB440** [comment] 2024-01-01 21:08
It won't be a plugin issue. It's a clientside thing. Unless you can provide reproduction steps on a vanilla client, nothing can be done.

**Comment by StKillReal** [comment] 2024-01-01 21:08
> It won't be a plugin issue. It's a clientside thing. Unless you can provide reproduction steps on a vanilla client, nothing can be done.

I tested all this on vanilla client

**Comment by StKillReal** [comment] 2024-01-01 21:08
I've cleared all server configs, all plugins and still have this issue

**Comment by SamB440** [comment] 2024-01-01 21:09
As I said, provide steps to reproduce this (what keys you pressed etc)

**Comment by StKillReal** [comment] 2024-01-01 21:10
> As I said, provide steps to reproduce this (what keys you pressed etc)

Okay, I'll send it after 10 minutes

**Comment by StKillReal** [comment] 2024-01-01 21:17
> As I said, provide steps to reproduce this (what keys you pressed etc)


https://github.com/GrimAnticheat/Grim/assets/60330193/a0ac5c17-0f2e-478c-8b84-82c311d296c3

**Comment by StKillReal** [comment] 2024-01-01 21:18
![image](https://github.com/GrimAnticheat/Grim/assets/60330193/0c4115fd-0808-45dd-ba0a-8db7dcd882d6)

**Comment by StKillReal** [comment] 2024-01-01 21:22
Tested on paper, nothing changed

**Comment by SamB440** [comment] 2024-01-02 18:30
I couldn't reproduce it before because I was using a 1.20.2 client, we should force false positive reports to include a client version imo

**Comment by SamB440** [comment] 2024-01-02 18:34
Fixed in https://github.com/GrimAnticheat/Grim/commit/01e36309a444b25be3b181ef70f9a626031d65b1

**Closed as completed** 2024-01-02 18:48 UTC
Labels: false positive

**Comment by StKillReal** [comment] 2024-01-03 15:35
> Fixed in [01e3630](https://github.com/GrimAnticheat/Grim/commit/01e36309a444b25be3b181ef70f9a626031d65b1)

Okay, but..
![image](https://github.com/GrimAnticheat/Grim/assets/60330193/338d4131-8a48-4908-9bcc-20b31849bdeb)

**Comment by SamB440** [comment] 2024-01-03 15:41
You need to compile against latest packetevents, I'm unsure how though
