### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by StKillReal** [GrimAnticheat/Grim#1279] opened 2023-12-30 12:31 UTC
### Stack trace

![image](https://github.com/GrimAnticheat/Grim/assets/60330193/2d76ff3d-be31-432f-b6d8-43f2d25e2a69)

### Grim version

2.3.50

### Server version

![image](https://github.com/GrimAnticheat/Grim/assets/60330193/21371cf3-eca8-46e0-af4a-68ab3cfb6382)

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/60330193/62f583bb-db09-4180-b05a-a8cb1263465e)

**Comment by SamB440** [comment] 2023-12-30 13:51
Duplicate of #1277

**Closed as completed** 2024-01-01 11:55 UTC
Labels: error
