### ISSUE TITLE
When grimac 2.3.51 is running on purpur-1.20.2-2095, tree chopping will have pullbacks and false positives

### ISSUE THREAD

**Issue by CNDogc** [GrimAnticheat/Grim#1282] opened 2023-12-31 17:19 UTC
### Describe the false positive and how to replicate it

When grimac 2.3.51 is running on purpur-1.20.2-2095, tree chopping will have pullbacks and false positives

### Grim version

grimac 2.3.51

### Server version

Current: git-Purpur-2095 (MC: 1.20.2)*
Previous: git-Purpur-2092 (MC: 1.20.2)
* You are running the latest version

### Plugins

Bukkit Plugins: (82): 
[01:17:58 INFO]:  - AdventCalendar, AureliumSkills, AuthMe, AuthMeTitles, BedrockPlayerSupport, BetterRTP, BungeeTabListPlus, Chunky, Citizens, CMILib 
[01:17:58 INFO]:  CommandBlocker, ConsoleSpamFix, CustomSprays, DecentHolograms, DeluxeMenus, eBackup, *EChatPapi, EnderDragon, Essentials, EssentialsChat 
[01:17:58 INFO]:  EssentialsSpawn, FightLogger, floodgate, GeyserHacks, GeyserSkinManager, GrimAC, GSit, GUIHelper, HolographicDisplays, *HungerKeeperPlus 
[01:17:58 INFO]:  InventoryRollbackPlus, ItemCommand, ItemsAdder, LiteSignIn, LockettePro, LoneLibs, LuckPerms, MCEEW, MiniMOTD, ModelEngine 
[01:17:58 INFO]:  Multiverse-Core, MythicMobs, NBTAPI, OpenInv, PartyGames, PlaceholderAPI, *PlayerPoints, PlayerTitle, PlayerTop, PlaytimeRewards 
[01:17:58 INFO]:  Prism, ProtocolLib, PvPManager, QuickShop, QuickShopForm, RayTraceAntiXray, RealisticSeasons, *RedPacketRain, ReleaseCommand, Residence 
[01:17:58 INFO]:  ResidenceForm, Scoreboard, Sentinel, ServerMonitor, SkinsRestorer, spark, *Stp, Tamablefoxes, *TDRPlaytime, Themis 
[01:17:58 INFO]:  Tpa, TrackMyMiner, UltraSetHome, Vault, VeinMiner, ViaBackwards, ViaRewind, ViaVersion, Vulcan, WkKit 
[01:17:58 INFO]:  WorldEdit, YukiNoaAPI

**Comment by CNDogc** [comment] 2023-12-31 17:25
And after my testing, the grimac-2.3.46 version does not have this problem

**Comment by SamB440** [comment] 2023-12-31 18:31
This is a duplicate of #1253 

2.3.51 doesn't truly have the latest packetevents changes, they need to publish a new version I believe

**Closed as completed** 2024-01-01 11:55 UTC
Labels: false positive
