### ISSUE TITLE
McMMO Super Breaker False Positive

### ISSUE THREAD

**Issue by TheMattVid** [GrimAnticheat/Grim#632] opened 2022-07-09 20:13 UTC
**Describe the bug**
Players are kicked, presumably for FastBreak, when using the Super Breaker ability in the McMMO plugin.

**Server Version:**
Paper 1.19.1

**Grim Version (Git commit or the version in the jar's name)**
2.3.10

**Relevant plugins**
McMMO

**Comment by MWHunter** [comment] 2022-07-10 17:36
Invalid bug report, you need to have at least the check that's flagging because I was unable to reproduce and have no clue where to even begin looking.  Perhaps if this is instabreak, then the fix in 2.3.11(discord only due to instability) with "Fixed issue when mining downwards and taking knockback."  In that case, if it was fixed in that update it would be a waste of time to try to debug an issue that doesn't exist.

**Closed as completed by MWHunter** 2022-07-10 17:36 UTC
Labels: bug

**Comment by TheMattVid** [comment] 2022-07-11 05:41
Yes, Super Breaker is an instabreak. I also learned from players that they were also getting kicked from using vanilla Minecraft kinds of instabreaks, which confirms what you referenced about this being a bug related to instabreaks which you already fixed in a new version not yet available on Spigot.
